POST http://localhost:8080/todos
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJlbWFpbEBlbWFpbC5jb20iLCJ1c2VyUm9sZSI6IlVTRVIiLCJuaWNrbmFtZSI6IuyViOuFle2VmOyEuOyalCIsImV4cCI6MTc2NjAyMjg1MCwiaWF0IjoxNzY2MDE5MjUwfQ.Baea0PMewmXCiBLeNY7yYb1RWsJOX7NyoZ5LelR6Jlg
Content-Type: application/json

{
  "title": "spring",
  "contents": "무슨 고민있어요?"
}

###
###
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
  "email": "email@email.com",
  "password": "Password!2",
  "userRole": "USER",
  "nickname": "안녕하세요"
}

###
@todoId = 1
GET http://localhost:8080/todos/{{todoId}}
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJlbWFpbEBlbWFpbC5jb20iLCJ1c2VyUm9sZSI6IlVTRVIiLCJuaWNrbmFtZSI6IuyViOuFle2VmOyEuOyalCIsImV4cCI6MTc2NjAyMjg1MCwiaWF0IjoxNzY2MDE5MjUwfQ.Baea0PMewmXCiBLeNY7yYb1RWsJOX7NyoZ5LelR6Jlg

###
GET http://localhost:8080/search?page=0&size=10&query=spring
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIxIiwiZW1haWwiOiJlbWFpbEBlbWFpbC5jb20iLCJ1c2VyUm9sZSI6IlVTRVIiLCJuaWNrbmFtZSI6IuyViOuFle2VmOyEuOyalCIsImV4cCI6MTc2NjAyMjg1MCwiaWF0IjoxNzY2MDE5MjUwfQ.Baea0PMewmXCiBLeNY7yYb1RWsJOX7NyoZ5LelR6Jlg
